### ISSUE TITLE
Citation has wrong version

### ISSUE THREAD

**Issue by hugoledoux** [evetion/SpaceLiDAR.jl#12]
https://github.com/evetion/SpaceLiDAR.jl/blob/4a9ca566b574f481a0d362c0b236de820bbe5800/CITATION.cff#L10

**Comment by evetion** [comment]
Thanks for catching this! Might be better to register Zenodo, which syncs up with GitHub releases.

**Comment by evetion** [comment]
Zenodo is now update to date 

https://doi.org/10.5281/zenodo.7260368
