### ISSUE TITLE
earthdata_search using geojson with POST

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#18]
Before I take a crack at this I wanted to see if you've already implemented a [polygon geojson/shapefile granule search](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-polygon) elsewhere?

**Comment by evetion** [comment]
I haven't, so feel free to try your hand at it. 👍

 I would advise to use GeoInterface for this and replace the current NamedTuple interface with Extents.

**Comment by evetion** [comment]
Moved to EarthData.jl
