### ISSUE TITLE
Should ATL08 return height and height_canopy

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#34]
Looking at the ATL08 code I'm wondering if it would be better to just always return ground (`height`) and canopy height (`height_canopy`)for consistency... this would simplify the code at the cost of 2 extra variables.  This would eliminate the `canopy` and `ground` key words arguments

**Comment by evetion** [comment]
I agree with you that it's a bit ugly in terms of complexity, but it has the advantage of performance. Changing this makes it also harder to be consistent with the `points` function for GEDI, as there are different lat/lon variables for ground/canopy in those datasets.
