### ISSUE TITLE
If download is killed early partail .h5 breaks workflow

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#35]
Because download! is writing directly to the final file name the workflow can result in partial or corrupt .h5 files. I will make a pull request to download to a temporary file then rename when complete.

**Comment by evetion** [comment]
How/why is the download killed early? Because if it's a CTRL-C, you could just catch it with a try/catch/finally.

For these issues I also advocate to use an external tool like `aria2c` in the [documentation](https://www.evetion.nl/SpaceLiDAR.jl/dev/guides/downloads/).

**Comment by alex-s-gardner** [comment]
In this case my laptop decided to have a kernel panic while reading in parallel (using `asyncmap`) which left a bunch of partial h5s scattered in my archive. 

Thanks for pointing me to `aria2c`.. that's absolutely fantastic. Hadn't stumbled on that yet.  I'll test out to see how much of a bump in speed I get.

Given past experience I still think it's worth accepting the PR to write to a temporary filename then rename. No cost in speed, but makes it more robust to crashes.
