### ISSUE TITLE
get(ENV, "AWS_SESSION_EXPIRES", typemin(DateTime)) returns a string not a DateTime 

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#42]
line 18 and 19 of `granule.jl` is: 

```julia
    expiry = get(ENV, "AWS_SESSION_EXPIRES", typemin(DateTime))
    if expiry < Dates.now(UTC)
```

but expiry::String and Dates.now(UTC)::Dates.DateTime so this line throws and error.

Changing line 18 to:
`expiry = DateTime(get(ENV, "AWS_SESSION_EXPIRES", typemin(DateTime)))`

should fix this

**Comment by evetion** [comment]
Thanks for catching this! I'm gonna put some EarthData credentials in Github actions to test all these functions, it's too error prone otherwise.

**Comment by evetion** [comment]
Fixed by https://github.com/evetion/SpaceLiDAR.jl/commit/0e322f6b6d022b0e482135a2d049b6defe559077
