### ISSUE TITLE
Thoughts on adding CryoSat support

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#43]
I'd like to include CryoSat data in my workflow.. what are your thought on adding CryoSat support in SpaceLiDAR?

**Comment by alex-s-gardner** [comment]
Python reader: https://github.com/tsutterley/read-cryosat-2
Matlab reader: https://earth.esa.int/eogateway/tools/cryosat-matlab-routines

**Comment by evetion** [comment]
It would be a bit odd, as CryoSat-2 isn't LiDAR, but radar? And thus also raster instead of vector (points)? I'd say it's a separate package.

**Comment by alex-s-gardner** [comment]
CryoSat and other Radar altimeters provide point based measurements like a laser altimeter but they are indeed not laser altimeters ... a more appropriately named package for both sensor types would be SpaceAltimetry

**Comment by evetion** [comment]
Would there be much overlap in implementing other altimeters? As in same search, granules of HDF5 files that give a spatial table with points? If so, I would be open to PRs that add it, otherwise a separate package makes more sense.

**Comment by alex-s-gardner** [comment]
Closing this for now as it would be a big lift and probably belongs in it's own package
