### ISSUE TITLE
Add s3 kwg for :GEDI ?

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#45]
I'm not sure if :GEDI data is yet available on s3 but I was wondering if you want to add the kwg now to search(:GEDI....) for consistency.. then when it does become available it will be work out of the box.

**Comment by evetion** [comment]
Thanks, that is a good suggestion. I believe level 4 data is available on s3 already.

**Comment by evetion** [comment]
Hmm, it's not _that_ easy, as the datacenter for new cloud collections is unknown. Some datasets are on ORNL_CLOUD, but LPCLOUD would also be a logical option.

**Comment by evetion** [comment]
Revisit once GEDI L2A has moved to S3.
