### ISSUE TITLE
List of breaking changes for rel 0.3

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#46]
Updates in new release look great... haven't fully tested them yet. I see there are a number of breaking changes in this release. it would be good to have a list of breaking changes to make it easier to update existing code.

**Comment by evetion** [comment]
Agreed, that's why there's https://www.evetion.nl/SpaceLiDAR.jl/stable/changelog/

But I think I managed to turn most changes into deprecation warnings only (not visible by default). The only real breaking change is that granules don't have the bbox field anymore.

**Comment by alex-s-gardner** [comment]
This is great, thanks.. didn't see that. The only other one that I've hit is that defining `Granule` now requires a polygon field.

**Comment by alex-s-gardner** [comment]
And `points` now accepts 'extent`

**Comment by alex-s-gardner** [comment]
version in `search` is now a 'Int' not a string

**Comment by alex-s-gardner** [comment]
Calling `GEDI_Granule` has change and now requires a `Type` declaration

**Comment by evetion** [comment]
Will test the next release a bit better, and also note which is breaking, and what not.
