### ISSUE TITLE
Should Lat and Lon be saved as Float32

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#60]
Lat and Lon only need Float32 precision

**Comment by evetion** [comment]
I think we want to keep the precision as provided by the granules? There's no way to read them in as Float32 in HDF5, so it doesn't matter whether SpaceLiDAR.jl converts them or you convert later on.

**Comment by alex-s-gardner** [comment]
agreed... closing
