### ISSUE TITLE
Download GEDI by extent error

### ISSUE THREAD

**Issue by jzphlp** [evetion/SpaceLiDAR.jl#67]
Hi there, I am new to Julia, and trying to download GEDI for a roi, but I am getting this error. Any help would be much appreciated. Thanks
![Screenshot from 2023-10-29 13-50-36](https://github.com/evetion/SpaceLiDAR.jl/assets/96884200/532761ae-2510-4412-955a-76fb982cfebe)

**Comment by evetion** [comment]
Welcome to Julia!

You define an Extent by providing the dimensions, like so:

```julia
vietnam = Extent(X = (102., 107.0), Y = (8.0, 12.0))
```

**Comment by jzphlp** [comment]
Thanks. I passed the dims like you said, but still not working. 
![Screenshot from 2023-11-04 15-02-25](https://github.com/evetion/SpaceLiDAR.jl/assets/96884200/5c1d9f20-060b-4ea6-98cc-87f48ba25c1d)

**Comment by evetion** [comment]
Might I suggest you paste code as text, and not as screenshots? You can use ``` to quote code, like so

```julia
granules = search(:GEDI, :GEDI02_A, vietnam)
```

Incidentally, the above code snippet should work. In your screenshot, you pass the `:bbox` (a symbol), while you should pass the Extent object (in your case, `vietnam`).

**Comment by jzphlp** [comment]
Thanks very much for your patience with this. Much appreciated!

Here is the code:

using SpaceLiDAR
using Extents
using DataFrames
#include("utils.jl")


# Define the extent for Can Tho, Vietnam
bbox = Extents(X = (105.77, 105.85), Y = (10.05, 10.15))
vietnam = Extent(X = (102., 107.0), Y = (8.0, 12.0))
granules = search(:ICESat2, :GEDI02_A,:bbox)

**Comment by alex-s-gardner** [comment]
It looks like this issue was resolved... closing
