### ISSUE TITLE
Could we add a way to trace points to originating granule?

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#74]
I need a way to trace from point data to originating granule. I hacked a solution on my end by appending the granule info to the NamedTuple returned by points but I'd like to move away from this and maybe just include the filename as a FillArray in the points Table.

I know we had discussed this in the past but forgot what we decided. 

Is now a good time to add a unique identifier?

**Comment by evetion** [comment]
On master we have the `add_info` and `add_id` methods to do exactly this 😄

**Comment by alex-s-gardner** [comment]
perfect.. thanks and apologies for missing that
